# Generated by Django 2.2.13 on 2020-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='stars',
            field=models.CharField(max_length=10),
        ),
    ]
